//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_Project_Week2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public string IsAvailable { get; set; }
        public string Path { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public string RentDate { get; set; }
        public string ReturnDate { get; set; }
        public Nullable<int> LastClientId { get; set; }
        public virtual Author Author { get; set; }
    }
}
